name = "ChartServer"
version = "0.2.0"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
CryptoMarketData = "57973c84-8724-49d2-9af5-7f2266b21095"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LightweightCharts = "d6998af1-87ca-4e7f-83d4-864c79a249fa"
MarketData = "945b72a4-3b13-509d-9b46-1525bb5c06de"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
NanoDates = "46f1a544-deae-4307-8689-c12aa3c955c6"
OnlineTechnicalIndicators = "dc2d07fb-478f-4566-8417-81bb3e5a7af1"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Rocket = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"
StringCases = "f22f4433-750e-5048-95f9-cae576f2c120"
TechnicalIndicatorCharts = "ffc6123f-ba44-4b2f-a8ce-46f3306b22af"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Visor = "cf786855-3531-4b86-ba6e-3e33dce7dcdb"
